### ISSUE TITLE
No connection to rTorrent. Check if it is really running. Check $scgi_port and $scgi_host settings in config.php and scgi_port in rTorrent configuration file.

### ISSUE THREAD

**Issue by piney-zz** [Kerwood/Rtorrent-Auto-Install#100]
Sorry for being a n00b.
Who knows what I've done wrong. I attempted to run the Raspbian script but it just has constant errors and dead links.

So I fresh installed Raspbian
Ran the Debian script
used Pi user
Selected all plugins
Ran install

Install finished
restarted pi after editing .rtorrent.rc

connected to rutorrent and get:
No connection to rTorrent. Check if it is really running. Check $scgi_port and $scgi_host settings in config.php and scgi_port in rTorrent configuration file.

I'm a linux novice just learning from making different projects

using "ps aux | less" I see no rtorrent?

-bash: rtorrent: command not found
rtorrent: unrecognized service

How do I start rtorrent?

Thanks for your time and install script to help n00bs like myself :D

**Comment by miracle091** [comment]
Is the apache2 version right?
Anyway check if this file exist <code>/etc/init.d/rtorrent-init</code>, if you don't find it, take it from this repo under the "Files" directory or with this command <code>wget -O /etc/init.d/rtorrent-init https://raw.github.com/Kerwood/rtorrent.auto.install/master/Files/rtorrent-init</code>

**Comment by piney** [comment]
Apache2 yes and rtorrent-init is there

rtorrentinit.log reads:

cannot find rtorrent binary in PATH /usr/bin:/usr/local/bin:/usr/local/sbin:/sbin:/bin:/usr/sbin

**Comment by miracle091** [comment]
Seem rtorrent is not installed...try run the install script again, need to patch the actual script with some more check

**Comment by piney** [comment]
Problem solved :+1: 

rtorrent was never installed.
Ran apt-get install rtorrent and now working I think.
I just presumed that was part of the script

**Comment by piney** [comment]
Thanks for your help :D

**Comment by miracle091** [comment]
Is part of the script install rtorrent, but from source and compile it, not take the .deb diretcly from debian repository, cause don't have xmlrpc, and is needed

**Comment by piney** [comment]
now I get "Storage error: [Hash checker was unable to map chunk: Permission denied]"

Time to give up on rtorrent raspberry pi

**Comment by topjes** [comment]
Been looking for days for a solution. I got rtorrent listening only on TCP6 ::1:5000 and changing "127.0.0.1" to "localhost" in "/var/www/rutorrent/conf/config.php" made it work finally!
