### ISSUE TITLE
Possibility to merge apache & nginx script

### ISSUE THREAD

**Issue by miracle091** [Kerwood/Rtorrent-Auto-Install#101]
In this days i am thinking to make a unique script (for raspberry, for now) to install apache or nginx for web server, make it choose when launch the script.

Anyone what this enhancement?

**Comment by jdupl** [comment]
Ideally, it would be nice to have only one script for all.

**Comment by Kerwood** [comment]
Would be cool, but maybe a bit confusing for new users.
