### ISSUE TITLE
Raspbian Jessie fresh install gives error

### ISSUE THREAD

**Issue by skyway22** [Kerwood/Rtorrent-Auto-Install#142]
Raspberry pi2 and samsung ultra card 10class.. gives me this.
Any ideeas?
Hash check on download completion found bad chunks, consider using \"safe_sync\".

**Comment by Kerwood** [comment]
Gives you what ?

**Comment by skyway22** [comment]
That hashcheck error. It only happends on large torrents i see. Above ~4 gb

**Comment by jdupl** [comment]
What is the filesystem ?

**Comment by skyway22** [comment]
/dev/sda1      fuseblk  976760000 610794896 365965104  63% /media/SAMSUNG - this is for my externat drive... and ext4 for /root part.
