### ISSUE TITLE
Ubuntu problems (downloading plugins, installing rtorrent, starting rtorrent)

### ISSUE THREAD

**Issue by redalert1848** [Kerwood/Rtorrent-Auto-Install#145]
1. The script won't install rtorrent at first run. Plus the first run of the script won't allow you to download all the plugins, it gives this error:
https://github.com/Kerwood/Rtorrent-Auto-Install/issues/137

2. When you run it again after the initial install you can download the plugins. Also rtorrent will be able to install.

3. When you restart the server rtorrent won't start automatically.
https://github.com/Kerwood/Rtorrent-Auto-Install/issues/132

Hopefully you will be able to fix these issues!

**Comment by Kerwood** [comment]
It's a Debian script, use Ubuntu at own risk.
