### ISSUE TITLE
Rutorrent/rtorrent crash

### ISSUE THREAD

**Issue by kanazaca** [Kerwood/Rtorrent-Auto-Install#151]
Hi,

When i start downloading some stuff the rutorrent keeps reloading, saying that lost connection to rtorrent and to check connection to scgi_port.

Thanks in advance.

**Comment by jdupl** [comment]
Can you test rtorrent only without webui ? Perhaps it will provide an error.

**Comment by kanazaca** [comment]
@jdupl ... Thanks for your time, but i already solved the error, i was using a network mount directory to save the downloads and it was slower and started to cache (using RAM) and the rtorrent crash's. After i changed to a normal download folder it started working properly.
