### ISSUE TITLE
Will we get an updated script for 16.04?

### ISSUE THREAD

**Issue by Pinholic** [Kerwood/Rtorrent-Auto-Install#152]
Is there an update in the pipeline?
Script now fails on ubuntu 16.04 LTS

**Comment by skyway22** [comment]
you could paste the error, that would be helpful..

**Comment by Pinholic** [comment]
Sorry am out at work at the moment. Will post the error tomorrow 😊

**Comment by Kerwood** [comment]
Nope.. The script was never meant for Ubuntu.. Use Debian instead or use the Docker container i created. Its quick and easy.
https://github.com/Kerwood/Rtorrent-LXC
