### ISSUE TITLE
XMLRPC doesn't download

### ISSUE THREAD

**Issue by netomx** [Kerwood/Rtorrent-Auto-Install#153]
It reportes: ERROR: not in gzip format

Solution, fo to the line 720 (aprox) and change the URL of XMLRPC to:

http://downloads.sourceforge.net/project/xmlrpc-c/Xmlrpc-c%20Super%20Stable/1.33.18/xmlrpc-c-1.33.18.tgz

**Comment by Kerwood** [comment]
Which script did you use ?

**Comment by Kerwood** [comment]
I dont seem to have any issues with the Jessie script.

**Comment by netomx** [comment]
The jessie one.

**Comment by Kerwood** [comment]
Cant reproduce the issue.
