### ISSUE TITLE
Can't find the directory "/home/apache"

### ISSUE THREAD

**Issue by myveb** [Kerwood/Rtorrent-Auto-Install#154]
When I have finished installation, there is no directory "/home/apache", so there are not files ".rtorrent.rc","downloads" and ".rtorrent-session".
I've copied a ".rtorrent.rc" to the position from the code. then there's another trouble, when I run the commond "service rtorrent-init start", it says that "cannot find readable session directory HOMEDIRHERE/.rtorrent-session from config /home/apache/.rtorrent.rc. check permissions".

**Comment by Kerwood** [comment]
Which Linux distro are you using ?

**Comment by Kerwood** [comment]
Did actually create a user named apache ?

**Comment by Kerwood** [comment]
I have no clue what you did. But what ever you did, it was dead wrong :) ..
Maybe you should use a default plain Debian 8 installation ?..
Or a Docker container. https://github.com/Kerwood/Rtorrent-LXC
