### ISSUE TITLE
Default setup

### ISSUE THREAD

**Issue by maestroi** [Kerwood/Rtorrent-Auto-Install#155]
I did the most basic setup, at first it destroyed my apache configuration, but i fixed that.

After i did a bit of research and i found out that the script tryed to install php5 wich does not install on ubuntu 16.04 lts

because of this SCGIMount Does not work,
Jun 10 01:33:28 sd-93980 apache2[41239]: AH00526: Syntax error on line 10 of /etc/apache2/sites-enabled/001-default-rutorrent.conf:
Jun 10 01:33:28 sd-93980 apache2[41239]: Invalid command 'SCGIMount', perhaps misspelled or defined by a module not included in the server configuration

I guess it needs a fix. its late atm so i cannot find a solution at this moment.

**Comment by Kerwood** [comment]
The "Debian" in the name of the scripts, indicate that they are only meant for Debian.
Do not try and use them on Ubuntu, they will most likely not work.

If you want to use rtorrent on other distro's. Use the Docker container i made.
https://hub.docker.com/r/kerwood/rtorrent-lxc/
