### ISSUE TITLE
Accessing from outside the network?

### ISSUE THREAD

**Issue by mbc0** [Kerwood/Rtorrent-Auto-Install#156]
Hi,

Firstly, many thanks for this script, it has appeared to install correctly and I can run it using VNC to my VPS.  How can I connect from outside though? I have used 62.***.***.***/rtorrent  (Purposely hidden) but get a page cannot be found? I have tried :5000 instead of /rtorrent also.

Many Thanks

**Comment by myveb** [comment]
you are chinese ?

**Comment by Kerwood** [comment]
The address is ***/rutorrent
Not rtorrent.

**Comment by mbc0** [comment]
My apologies! that was a typo! I am using 62.***.***.**/rutorrent but get  

"This site can’t be reached 62.***.***.** took too long to respond."

if I type the same address locally on the VPS via VNC I instantly the login box

is there no actual port number like on my rutorrent installation on my unRAID server?

Thanks for the replies.. (even the Chinese one? XD)

**Comment by Kerwood** [comment]
Nope.. Something is blocking your connection on port 80 to your server.

**Comment by mbc0** [comment]
ok, thank you, being a vps I dont think I will be able to change that, is there a config file where I can change to a different port?

Thank you

**Comment by Kerwood** [comment]
It would be really weird if you dont have access to port 80.
If you want to change the port, you need you change the port for your webservice, Apache.

**Comment by mbc0** [comment]
I just tried this from my VPS, so it looks to be open?

Starting Nmap 6.40 ( http://nmap.org ) at 2016-06-14 09:08 BST
Nmap scan report for localhost (127.0.0.1)
Host is up (0.00022s latency).
Other addresses for localhost (not scanned): 127.0.0.1
Not shown: 988 closed ports
PORT     STATE SERVICE
80/tcp   open  http
111/tcp  open  rpcbind
139/tcp  open  netbios-ssn
443/tcp  open  https
445/tcp  open  microsoft-ds
631/tcp  open  ipp
5000/tcp open  upnp
5050/tcp open  mmcc
5901/tcp open  vnc-1
6001/tcp open  X11:1
8181/tcp open  unknown
9091/tcp open  xmltec-xmlmail
No exact OS matches for host (If you know what OS is running on it, see http://nmap.org/submit/ ).

Any idea? 

Thanks for your help so far...

**Comment by maestroi** [comment]
MBC0 you scanned on your local hosts for ports but try outside to scan your VPS.

so you can test what works!
use nmap on your local machine and scan the vps and post results

**Comment by mbc0** [comment]
Hi, I am sorry, I do not understand what you mean? I ran that command from the VPS Console that rutorrent is running on how would I scan my VPS from my local machine?

Thanks
