### ISSUE TITLE
Debian 8 Installation

### ISSUE THREAD

**Issue by aboutnet** [Kerwood/Rtorrent-Auto-Install#158]
The script don't created all config and directory! .rutorrent.rc Download/  etc..

**Comment by Kerwood** [comment]
Yes it does.

**Comment by aboutnet** [comment]
I put "mayhem" as system user whereis  located in /home/mayhem, The install script said it install all  file in /home/outlaw/mayhem (not the  good path,  outlaw it's another system user) I  look in /home/outlaw/mayhem then /home/mayhem no .rc, Downloads folder!

**Comment by Kerwood** [comment]
Hmm that's weird. Cant really help you with this one. 
Was it on a clean Debian install ?
