### ISSUE TITLE
Auto installer fails when installing PHP5 on Ubuntu 16 (xenial)

### ISSUE THREAD

**Issue by poopsock** [Kerwood/Rtorrent-Auto-Install#160]
The auto installer fails when trying to install PHP5 on Ubuntu 16 (xenial):

```
E: Package 'php5' has no installation candidate
E: Unable to locate package php5-curl
E: Package 'php5-cli' has no installation candidate
E: Package 'libapache2-mod-php5' has no installation candidate
```

It turns out PHP5 is not included on xenial, so I had to first add the PHP5 PPA and then add all the PHP5 packages manually:

```
sudo add-apt-repository ppa:ondrej/php
sudo apt-get update
sudo apt-get install php5.6 php5.6-cli php5.6-curl libapache2-mod-php5.6 libapache2-mod-scgi
```

Source of where I got the PPA and package syntax info: http://askubuntu.com/a/756186

**Rtorrent also failed at making/installing, so I had to install it manually from apt and then re-run the autoinstall script**. Everything worked normally after the script finished.

After doing all that, I was able to download a torrent successfully.

**Comment by Kerwood** [comment]
The script is not made for Ubuntu. 
Alternatively you can use the Docker container I made. 
https://github.com/Kerwood/Rtorrent-LXC

**Comment by poopsock** [comment]
Ok, but it ended up working after running the commands above and then running the install script. So, if anyone else on Ubuntu wants to give it a shot, it might work for them too.
