### ISSUE TITLE
Adapt script to Ubuntu 16.04

### ISSUE THREAD

**Issue by enoch85** [Kerwood/Rtorrent-Auto-Install#161]
Would be great if you could adapt the script to Ubuntu 16.04, a reminder is that php5 is not used, but php7 is.

Thanks for a great script!

**Comment by Kerwood** [comment]
Not gonna happen from my side :) .. But you are welcome to fork the project.. 
Or the easiest way would be just to use the Docker container I've made. 
https://github.com/Kerwood/Rtorrent-LXC

**Comment by enoch85** [comment]
Thanks, will fork.
