### ISSUE TITLE
request to add modify or repair

### ISSUE THREAD

**Issue by checktravis** [Kerwood/Rtorrent-Auto-Install#164]
this script is so very helpful. i am on a pine64 and it's hard to find support for all the pieces but your script here is a piece of cake.

the only thing is it take so long to install. and, once it was installed it worked with no issues. then. i was trying to modify some permissions (to get it working with plex, NFS, etc) and I broke it. I spent some time figuring out what wasn't working but ended up just running this script again and it fixed it. I did this again after I messed up the config file :)

i like how you have a separate installer for plugins, can there be something like that to repair or change an installation that doesn't have to recreate everything?

**Comment by Kerwood** [comment]
Hi mate.. The script isn't really maintained any more. 
Personally I'm using the Docker container I made.
