### ISSUE TITLE
Not Connection!!

### ISSUE THREAD

**Issue by Smallkan** [Kerwood/Rtorrent-Auto-Install#169]
Error:
[29.09.2016 00:14:23] No connection to rTorrent. Check if it is really running. Check $scgi_port and $scgi_host settings in config.php and scgi_port in rTorrent configuration file.

Help Please!

**Comment by Kerwood** [comment]
What Linux distro are you using ?

**Comment by gallok** [comment]
Same here in a Debian Jessie ARM

**Comment by awo-dev** [comment]
I have the same issue in Debian Jessie ARM (on my Raspberry Pi).

`sudo uname -a` gives me: `Linux rpi-nas 4.4.26-v7+ #915 SMP Thu Oct 20 17:08:44 BST 2016 armv7l GNU/Linux`

**Comment by Jayphen** [comment]
Same, also with Jessie

**Comment by Kerwood** [comment]
I would expect it on Debian ARM... But there are no issues on a clean Debian Jessie 64bit.

**Comment by awo-dev** [comment]
I'm just running Raspbian Jessie. I used to be able to run it without issues on Raspbian Wheezy, but after reinstalling my raspberry pi, and installing Raspbian Jessie Lite, I couldn't get it working.

**Comment by Kerwood** [comment]
Cant really help you guys.. The script is only supported on standard Debian Jessie x64. And Im not developing on the any more.. Maybe try and use the Docker container i made ?
