### ISSUE TITLE
Problem with rutorrent

### ISSUE THREAD

**Issue by giacomofabbri** [Kerwood/Rtorrent-Auto-Install#171]
Hi! I hope that someone will help me, anyway I used your awesome tool to install rtorrent+rutorrent, I'm pretty sure rtorrent works because I'm able to connect using [Nativa](https://bitbucket.org/vovasty/nativa) and it works, the problem it's with rutorrent, I'm not using Apache but nginx, I don't know if that's the problem, but I'm not able at all to connect neither using Apache neither using nginx! Could you possibly help me please??
I'm desperate!
If you can't actually help me, could you at last tell me how to completely remove all traces of your script and everything linked to please! Thanks man

**Comment by gallok** [comment]
Same here

**Comment by giacomofabbri** [comment]
I decided to go back to Deluge, much easier and it's pretty good!!
