### ISSUE TITLE
HTTPS?

### ISSUE THREAD

**Issue by milltertime** [Kerwood/Rtorrent-Auto-Install#173]
Is there any chance for a HTTPS:// guide or suggestion on how to have the server be https?

**Comment by Kerwood** [comment]
You need to find a guide on how to setup SSL on Apache2.
I've made a guide en danish.. Google translate ? :)
https://linuxbloggen.dk/https-ssl-paa-apache-debian-7/

**Comment by milltertime** [comment]
Sounds like a good challenge!
