### ISSUE TITLE
Pleae type a valid system username

### ISSUE THREAD

**Issue by Quickboxfan** [Kerwood/Rtorrent-Auto-Install#179]
#i get this error in between installing script,i tried kerwood but it didnt start,i have not set any username for my vps yet

i get this user does not exist
Please type valid system username

https://s2.postimg.org/6z36joz1l/issues.png

**Comment by Kerwood** [comment]
You will have to create a user on your server. Rtorrent will be running on that user.
You cannot use `root`

**Comment by Quickboxfan** [comment]
yes thanks and i did that after reaching final step,i choose to install all plugins and as my box didnt start i remove httprpc,rpc and rebooted,still not login?
