### ISSUE TITLE
Error after login

### ISSUE THREAD

**Issue by Quickboxfan** [Kerwood/Rtorrent-Auto-Install#180]
1) i dont see download directory,i want to download my files via downlaod manager to my Pc

2) https://s16.postimg.org/d5piqas91/log.png how to exit this

**Comment by Kerwood** [comment]
Not sure what you mean by no. 1
For use of rtorrent see https://github.com/rakshasa/rtorrent/wiki/User-Guide
I think it is ctrl+q

**Comment by Quickboxfan** [comment]
sorry for my poor description,my first question was,i cannot locate my download directory,so that from seedbox i can download in my computer

**Comment by Kerwood** [comment]
The Download folder is located in your home folder.

**Comment by Quickboxfan** [comment]
yes that i got it,but i require to find my exact path,as i have install this script for first time in my lifetime so i m initially facing this issue,unable to locate path

can u tell me path in terms of "https://server_ip/*********"

**Comment by Kerwood** [comment]
You cant get to your downloaded folder via http.

**Comment by Quickboxfan** [comment]
i want to open download directory in WEB BROWSER,how can i do that

**Comment by Kerwood** [comment]
No
