### ISSUE TITLE
Syntax error:newline unexpected

### ISSUE THREAD

**Issue by Quickboxfan** [Kerwood/Rtorrent-Auto-Install#181]
./Rtorrent-Auto-Install-4.0.0-Debian-Wheezy: 8: ./Rtorrent-Auto-Install-4.0.0-Debian-Wheezy: Syntax error: newline unexpected

i have used debian jessy too and i face same errror with tha script

this occur at step : "sudo ./Rtorrent-Auto-Install-X.X.X-Debian-*******"

above error is on ubuntu,so i install  #centos

==============================================================

i have reinstall os on centos i get this connection time out?

![wh](https://user-images.githubusercontent.com/29623645/28067759-33a310e6-6660-11e7-9172-365aaf3a364d.png)
#180 
i have show my ls,jus check everything is ok or not i also tried removing plugings httprpc,rpc

**Comment by Kerwood** [comment]
The script only works on Debian.. Not Ubuntu, not CentOS.

**Comment by Quickboxfan** [comment]
what about first part which i did on ubuntu

**Comment by Kerwood** [comment]
The script only works on Debian.. Not **Ubuntu**, not CentOS.

**Comment by Quickboxfan** [comment]
first part was done on ubuntu,then itried centos

**Comment by Kerwood** [comment]
Install Debian 8 (Jessie) and download the script via the raw link.
https://raw.githubusercontent.com/Kerwood/Rtorrent-Auto-Install/master/Rtorrent-Auto-Install-4.0.0-Debian-Jessie

The script only works on Debian.. **_Not Ubuntu_**, not CentOS.

**Comment by Quickboxfan** [comment]
ok thanks

**Comment by Quickboxfan** [comment]
where can i find script for ubuntu?

**Comment by Quickboxfan** [comment]
pls help,i m struggling since longer time for this

**Comment by Quickboxfan** [comment]
sorry again for multiple post

**Comment by Quickboxfan** [comment]
"Your default Apache2 vhost file has been disabled and replaced with a new one.
If you were using it, combine the default and rutorrent vhost file and enable it again."

i got this error with debian 8 and above script

**Comment by Kerwood** [comment]
Damn you are one annoying person....
That is not an error.

**Comment by Quickboxfan** [comment]
sir i m annoying because i m just making errors,i m new to it and i have no intentions to trouble you,thanks for your valuable time and patience,may god bless you and u keep helping others :)

pls lock this topic and dont lose ur mind there are other who requires your help and i m sure u will provide with your utmost expertise

**Comment by Kerwood** [comment]
Thank you sir, you are much to kind.
May I give the advice of taking some time thinking about thou issue before asking the internet.
And do some research about what you are trying to accomplish before.

Any maybe if the script says "_Script for Debian..._", dont expect support for other distro's. Especially not CentOS.
