### ISSUE TITLE
Syntax error: newline unexpected

### ISSUE THREAD

**Issue by Pawelecc** [Kerwood/Rtorrent-Auto-Install#183]
Debian Jessie,

sudo ./Rtorrent-Auto-Install-4.0.0-Debian-Jessie

_Syntax error: newline unexpected_

Please help. What am I doing wrong?

**Comment by Kerwood** [comment]
How did you download the script ?.. You did not download it properly.

**Comment by Pawelecc** [comment]
I was giving a bad download address, my mistake.

In the Jessie version the rutorrent directory is /var/www/html/rutorrent or var/www/rutorrent?

**Comment by Kerwood** [comment]
`/var/www/html/rutorrent`
