### ISSUE TITLE
Makefile optimisation for Raspberry Pi

### ISSUE THREAD

**Issue by miracle091** [Kerwood/Rtorrent-Auto-Install#82]
Just the title say, i have tried some CFLAGS, but don't have anymore a model A (is dead yesterday...), now i have only a B+ alive.

Anyway this is the best (time vs size vs post-install perfomance) options i have found, if someone want to try it just add it inside the INSTALL_RTORRENT function and before any make:

<code>export CFLAGS="-march=armv6 -mtune=arm1176jzf-s -mfloat-abi=hard -mfpu=vfp -ffast-math -pipe -O3"</code>

<b>This settings overwrite, temporarily, the default CFLAGS and CXXFLAGS of the system.
To reset it just reboot the system.</b>

**Comment by miracle091** [comment]
This is the makefile time with the above flags on a model B+:
Compiled with <code>gcc version 4.6.3 (Debian 4.6.3-14+rpi1)</code>
<pre><code>xmlrpc-c --disable-cplusplus
taken from svn stable rev 2745

real    0m10.366s
user    0m3.520s
sys     0m2.900s
</code></pre>

<pre><code>libtorrent 0.13.4

real    0m8.440s
user    0m5.790s
sys     0m1.410s
</code></pre>

<pre><code>rtorrent 0.9.4 --prefix=/usr --with-xmlrpc-c

real    0m7.022s
user    0m3.560s
sys     0m1.120s
</code></pre>

**Comment by miracle091** [comment]
This in theory ( i don't own a rpi2 for now) is a possible choise for RPI2:
<code>export CFLAGS="-mcpu=cortex-a7 -mfpu=neon-vfpv4 -mfloat-abi=hard -funsafe-math-optimizations -O3"</code>

Otherwise this:
<code>export CFLAGS="-march=armv7-a -mfpu=vfpv4 -mfloat-abi=hard -funsafe-math-optimizations -O3</code>

P.S. can be used, for what i have read on the official forum, the -O4 optimization instead of -O3, but i don't know if it impact the compilation size/time a lot or a just a little

**Comment by Kerwood** [comment]
Can this be closed ?

**Comment by miracle091** [comment]
Yes, in the next days i commit this changes
