### ISSUE TITLE
Raspberry Pi (Debian-like distro only) install script

### ISSUE THREAD

**Issue by miracle091** [Kerwood/Rtorrent-Auto-Install#89]
https://gist.github.com/miracle091/61aa929646bd5a3afed9

Instead of doing a pull, i have created a gist because is more easy for everyone to modify, anyway this is the latest version for the install script for raspberry pi.

It's install:
<b>Nginx
Rtorrent (with libtorrent and xmlrpc-c)
Rutorrent (with plugins if chosen)</b>

Remove:
<b>Apache2 (if it's installed)</b>

Need help testing it and find a way to make it better.

**Comment by zovt** [comment]
Hey, quick notice: I ran the Raspbian script, and it can't seem to find `rtorrent`. Where does the binary get installed?

**Comment by miracle091** [comment]
Updated lost some passage inside the install_rtorrent function. now is working.

**Comment by zovt** [comment]
I noticed that the RPi 2 cflags were commented out. Should I uncomment them before running the script?

**Comment by miracle091** [comment]
Yes and comment the flags for rpi b.

**Comment by zovt** [comment]
Yep, ok one second. I'll run it and report back.

**Comment by miracle091** [comment]
In theory ill need like 15-20 minutes for complete all the compilation.

**Comment by zovt** [comment]
True. I'll modify it so the make commands are using -j2

**Comment by miracle091** [comment]
If i remember well you can use -j3, cause it's a quad core no?

**Comment by zovt** [comment]
Yeah, I suppose this could be a good time to stress-test the compilation on the Pi2

**Comment by zovt** [comment]
Also, perhaps this should be a separate bug-report/feature-request, but it would be super nice to have an option to install all plugins EXCEPT a few

**Comment by miracle091** [comment]
Open a new issue for this. Thanks

**Comment by zovt** [comment]
`checking whether the C compiler works... no
configure: error: in `/tmp/xmlrpc':
configure: error: C compiler cannot create executables
See `config.log' for more details
`

I suspect this has something to do with the cflags. This was with the first set uncommented, so I'll try the second set now

**Comment by zovt** [comment]
Yep, looks like the second set of CFlags for RPi 2 worked. Compiling now

**Comment by miracle091** [comment]
The problem maybe is this two flags...
<code>-mcpu=cortex-a7 -mfpu=neon-vfpv4</code>

**Comment by miracle091** [comment]
After this can you try this CFLAGS? 

<code>export CFLAGS="-march=armv7-a -mfpu=neon-vfpv4 -mfloat-abi=hard -funsafe-math-optimizations -O3"</code>

**Comment by zovt** [comment]
sure thing! Let me make sure this set gets it up and running first

**Comment by miracle091** [comment]
Ah, it install <code>screen</code> for make it run, but you can try/use <code>tmux</code>.

**Comment by zovt** [comment]
```
make[1]: Leaving directory '/tmp/rtorrent/libtorrent-0.13.4'
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   124    0   124    0     0    709      0 --:--:-- --:--:-- --:--:--   892
100  220k  100  220k    0     0   489k      0 --:--:-- --:--:-- --:--:--  489k
curl: (6) Couldn't resolve host 'rtorrent-0.9.4.tar.gz'
tar (child): rtorrent-0.9.4.tar.gz: Cannot open: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now
./rpitorrent.sh: line 746: cd: rtorrent-0.9.4: No such file or directory
./rpitorrent.sh: line 747: ./autogen.sh: No such file or directory
./rpitorrent.sh: line 748: ./configure: No such file or directory
make: *** No targets specified and no makefile found.  Stop.
make: *** No rule to make target 'install'.  Stop.
rm: cannot remove `rtorrent': No such file or directory
```
Looks like an error when trying to download/install rtorrent

**Comment by miracle091** [comment]
Change line 744 with this:
<code>curl -L https://github.com/rakshasa/rtorrent/archive/0.9.4.tar.gz -o rtorrent-0.9.4.tar.gz/code>

**Comment by zovt** [comment]
Yep, that's what I did. It's rerunning now

**Comment by zovt** [comment]
Still failing to compile rtorrent due to the XMLRPC test

**Comment by miracle091** [comment]
Post the error, on rpi b work.

**Comment by zovt** [comment]
```
checking for XMLRPC-C... failed
configure: error: Could not compile XMLRPC-C test.
```

**Comment by zovt** [comment]
I'll try recompiling XMLRPC-C from source

**Comment by zovt** [comment]
Still the same error

**Comment by miracle091** [comment]
Reboot and try with the default cflags

**Comment by zovt** [comment]
Still no dice :disappointed:

**Comment by miracle091** [comment]
Your distro is wheezy based or Jessie?

**Comment by zovt** [comment]
Wheezy

**Comment by miracle091** [comment]
Is customized or is a normal raspbian?

**Comment by zovt** [comment]
Normal

**Comment by miracle091** [comment]
GCC version?

**Comment by zovt** [comment]
```
gcc --version
gcc (Debian 4.6.3-14+rpi1) 4.6.3
Copyright (C) 2011 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

```

**Comment by miracle091** [comment]
Try with a plain ./configure for xmlrpc-c

**Comment by zovt** [comment]
Nope, not that either

**Comment by miracle091** [comment]
Have tried to re-download the source?

**Comment by zovt** [comment]
yep, I don't know what's wrong. If I figure it out, I'll let you know. Thanks for the help.

**Comment by zovt** [comment]
figured it out: it's not a problem with xmlrpc-c, it's actually something with libtorrent. Compile libtorrent with --disable-instrumentation and it's good to go

**Comment by zovt** [comment]
Idk if this is related, but I'm now getting a 
```
[12.06.2015 17:36:08] WebUI started.
[12.06.2015 17:36:08] Bad response from server: (502 [error,getplugins]) Bad Gateway
[12.06.2015 17:36:08] Bad response from server: (502 [error,getuisettings]) <html> <head><title>502 Bad Gateway</title></head> <body bgcolor="white"> <center><h1>502 Bad Gateway</h1></center> <hr><center>nginx/1.7.0</center> </body> </html> 
```
Error in the log in rutorrent

**Comment by miracle091** [comment]
The error from rutorrent is because rtorrent is not started, is normal this script don't have a run script for rtorrent

**Comment by miracle091** [comment]
Updated the gist for showing the rpi version/revision and ram.

**Comment by ChrisSwan** [comment]
To solve the xmlrpc issue I found that I had to .configure libtorrent with --disable-instrumentation added to the parameter list.

**Comment by miracle091** [comment]
What `--disable-instrumentation` do?

**Comment by thomastoye** [comment]
Compiling `libtorrent` with `--disable-instrumentation` helped for me :+1:

**Comment by martasw** [comment]
Hi,
can anyone explain how to compile libtorrent with -disable-instrumentation for me? I'm pretty new in this.  

Thank you for help.

**Comment by AdvilCasual** [comment]
Same question, how do we add --disable-instrumentation to the parameter list in this script?
